### PR TITLE
Gh action tsc

### PR DESCRIPTION
**Pull request by lifekaizen**
@robotoer you may want to confirm the output looks correct: https://github.com/collabswarm/collabswarm/runs/3199040701?check_suite_focus=true

And maybe you know a better way to only check changed workspaces - but since they can run in parallel it seems fine.

Lastly, caching of npm-modules does not seem to be working (each workspace is taking 20s to yarn install), but can run in parallel so total time ~ 1 min.

### CODE REVIEW

**Comment by robotoer** [comment]
This output does not look correct:
```
Error: bin/collabswarm-yjs-d.ts(3,47): error TS2307: Cannot find module '@collabswarm/collabswarm' or its corresponding type declarations.
Error: src/collabswarm-yjs.ts(9,8): error TS2307: Cannot find module '@collabswarm/collabswarm' or its corresponding type declarations.
Error: Process completed with exit code 2.
```

My guess is that the wrong version of yarn/npm/nodejs is being used. Check out the `Dockerfile` for what gets setup for the dev environment.



Each github actions run creates a new docker container (think: new machine), clones the repo and runs whatever commands are specified in github actions. There is no shared filesystem or data between pipeline runs unfortunately. We'll need to use the github actions `cache` feature (or someone's prebuilt solution)

**Comment by robotoer** [comment]
Ah, the last run looks correct

**Review by robotoer — APPROVED** [review]

**Comment by lifekaizen** [comment]
Hmmm, I see what you mean. It's a different output than I get locally. Will check the Docker file and `cache` again.

**Comment by lifekaizen** [comment]
Confirmed working: https://github.com/collabswarm/collabswarm/actions/runs/1083225677

**Pull request merged**
